chore: update lockfile (#1501)
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1937

## 📔 Objective

Use `cargo update -p reqwest-middleware --precise 0.4.2` because we need
to match the [pinned version in
sdk-internal](https://github.com/bitwarden/sdk-internal/blob/e6e46d1a19d2070c6d6b1ee622b3ebe854f8186e/Cargo.lock#L4573-L4575).
Otherwise, build failures like the below will happen:

```
error[E0599]: no method named `query` found for struct `reqwest_middleware::client::RequestBuilder` in the current scope
    --> /home/user/.cargo/git/checkouts/sdk-internal-7795c51bce9e11e7/73cc150/crates/bitwarden-api-api/src/apis/organization_billing_v_next_api.rs:2151:39
     |
2151 |                 local_var_req_builder.query(&[("seats", &param_value.to_string())]);
     |                                       ^^^^^ method not found in `reqwest_middleware::client::RequestBuilder`
```